spring:
    application:
        name: inventory-failover-service
server:
    port: 8084

eureka:
    client:
        serviceUrl:
            #            default value
            defaultZone: http://localhost:8761/eureka