spring:
    application:
        name: inventory-failover-service
    zipkin:
        enabled: false
server:
    port: 8084

eureka:
    client:
        serviceUrl:
            #            default value + 'netflix' is an username and 'eureka' is a password via base authentication
            defaultZone: http://netflix:eureka@localhost:8761/eureka