spring:
    application:
        name: inventory-failover-service
    zipkin:
        base-url: http://localhost:9411/
server:
    port: 8084

eureka:
    client:
        serviceUrl:
            #            default value
            defaultZone: http://localhost:8761/eureka